package com.solutions5060.aria.bridge

import android.util.Log

/**
 * Bridge to the aria-mobile-core Rust library via UniFFI-generated Kotlin bindings.
 *
 * The actual UniFFI-generated Kotlin file will be at:
 *   bridge/uniffi/aria_mobile/aria_mobile.kt
 *
 * Generated by running:
 *   cargo run --features=uniffi/cli -- generate \
 *     --library target/aarch64-linux-android/release/libaria_mobile_core.so \
 *     --language kotlin \
 *     --out-dir ../aria-android/app/src/main/kotlin/com/solutions5060/aria/bridge/uniffi/
 *
 * This file provides convenience wrappers. In production, the UniFFI-generated
 * code replaces the stub implementations below.
 */
object AriaMobileCore {
    private const val TAG = "AriaMobileCore"

    init {
        try {
            System.loadLibrary("aria_mobile_core")
            Log.i(TAG, "Loaded aria_mobile_core native library")
        } catch (e: UnsatisfiedLinkError) {
            Log.w(TAG, "Native library not found — using stubs: ${e.message}")
        }
    }

    fun initRuntime() {
        Log.i(TAG, "Initializing Rust runtime")
        // Calls into UniFFI-generated: aria_mobile.initRuntime()
        try {
            initRuntimeNative()
        } catch (e: Exception) {
            Log.w(TAG, "initRuntime stub — native not linked")
        }
    }

    fun shutdownRuntime() {
        Log.i(TAG, "Shutting down Rust runtime")
        try {
            shutdownRuntimeNative()
        } catch (e: Exception) {
            Log.w(TAG, "shutdownRuntime stub")
        }
    }

    // Native method stubs — replaced by UniFFI generation
    private external fun initRuntimeNative()
    private external fun shutdownRuntimeNative()
}

// ── UniFFI Stub Types (replaced by generated code at build time) ─────────

data class GatewayConfig(
    val baseUrl: String,
    val apiKey: String,
)

data class SipCredentials(
    val username: String,
    val password: String,
    val domain: String,
    val registrar: String? = null,
    val transport: String = "udp",
    val port: UShort = 5060u,
    val authUsername: String? = null,
    val displayName: String = "",
)

data class DeviceRegistration(
    val platform: String,
    val pushToken: String,
    val bundleId: String? = null,
    val sip: SipCredentials,
)

data class DeviceRegistrationResponse(
    val deviceId: String,
    val authToken: String,
)

data class CallOffer(
    val callToken: String,
    val callerUri: String,
    val callerName: String? = null,
    val sdpOffer: String,
)

enum class CallState {
    Idle, Incoming, Ringing, Connecting, Connected, OnHold, Ended
}

enum class CallDirection {
    Inbound, Outbound
}

data class CallInfo(
    val callId: String,
    val remoteUri: String,
    val remoteName: String? = null,
    val state: CallState,
    val direction: CallDirection,
    val muted: Boolean = false,
    val onHold: Boolean = false,
    val durationSecs: ULong = 0u,
)

enum class AudioCodec {
    Pcmu, Pcma, Opus, G729
}

data class MediaStats(
    val packetsSent: ULong = 0u,
    val packetsReceived: ULong = 0u,
    val bytesSent: ULong = 0u,
    val bytesReceived: ULong = 0u,
    val jitterMs: Double = 0.0,
    val packetLoss: UInt = 0u,
    val rttMs: Double = 0.0,
)

data class PushCallPayload(
    val callToken: String,
    val callerUri: String,
    val callerName: String? = null,
    val gatewayUrl: String,
)

sealed class MobileError : Exception() {
    class NetworkError : MobileError()
    class AuthenticationError : MobileError()
    class RegistrationFailed : MobileError()
    class CallFailed : MobileError()
    class MediaError : MobileError()
    class InvalidState : MobileError()
    class GatewayError : MobileError()
    class Timeout : MobileError()
}

interface MobileEventHandler {
    fun onRegistrationChanged(deviceId: String, status: String, error: String?)
    fun onIncomingCall(offer: CallOffer)
    fun onCallStateChanged(info: CallInfo)
    fun onMediaStats(callId: String, stats: MediaStats)
    fun onError(context: String, message: String)
}

/**
 * Stub engine — replaced by UniFFI-generated AriaMobileEngine class.
 */
class AriaMobileEngine(private val gatewayConfig: GatewayConfig) {
    private var eventHandler: MobileEventHandler? = null

    fun setEventHandler(handler: MobileEventHandler) {
        eventHandler = handler
    }

    @Throws(MobileError::class)
    fun registerDevice(registration: DeviceRegistration): DeviceRegistrationResponse {
        return DeviceRegistrationResponse(deviceId = "stub", authToken = "stub")
    }

    @Throws(MobileError::class)
    fun unregisterDevice(deviceId: String) {}

    @Throws(MobileError::class)
    fun updatePushToken(deviceId: String, newToken: String) {}

    @Throws(MobileError::class)
    fun handlePushNotification(payload: PushCallPayload): CallOffer {
        return CallOffer(callToken = "", callerUri = "", sdpOffer = "")
    }

    @Throws(MobileError::class)
    fun acceptIncomingCall(callToken: String, preferredCodecs: List<AudioCodec>): CallInfo {
        return CallInfo(callId = "", remoteUri = "", state = CallState.Connected, direction = CallDirection.Inbound)
    }

    @Throws(MobileError::class)
    fun rejectIncomingCall(callToken: String) {}

    @Throws(MobileError::class)
    fun makeCall(uri: String, credentials: SipCredentials, preferredCodecs: List<AudioCodec>): CallInfo {
        return CallInfo(callId = "", remoteUri = uri, state = CallState.Ringing, direction = CallDirection.Outbound)
    }

    @Throws(MobileError::class)
    fun hangup(callId: String) {}

    @Throws(MobileError::class)
    fun setMute(callId: String, muted: Boolean) {}

    @Throws(MobileError::class)
    fun setHold(callId: String, onHold: Boolean) {}

    @Throws(MobileError::class)
    fun sendDtmf(callId: String, digit: String) {}

    fun getActiveCall(): CallInfo? = null
    fun getMediaStats(callId: String): MediaStats? = null
    fun setCodecPreferences(codecs: List<AudioCodec>) {}
}
